### ISSUE TITLE
Error | cannot read display_name of undefined

### ISSUE THREAD

**Issue by danverde** [byuitechops/build-file-structure#1]
Found on course with Brightspace OU 63194

```
cannot read property 'display_name' of undefined stack: TypeError: Cannot read property 'display_name' of undefined
    at Promise (c:\Users\danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\build-file-structure\main.js:148:67)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by danverde** [comment]
It happens all the time actually

**Comment by danverde** [comment]
https://github.com/byuitechops/build-file-structure/blob/d623194fbaa2c2260ba42075da43511104f05f8e/main.js#L147

It's because we delete the file, then try to access it.

**Comment by csammcgrath** [comment]
Fixed in commit https://github.com/byuitechops/build-file-structure/commit/69f1255ddfe81fa327f4fcb5651a653206e80181

@danverde, can you please check this and make sure that it works? Thank you!

**Comment by danverde** [comment]
Looks good!
